version: "2"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  memory: 512
virtualmachines:
- name: nixagent
  image: centos-7-v20201014
  shell: /bin/bash
  machine_type: n1-standard-1
- name: puppet
  image: kmo-instruqt/puppet
  shell: /bin/bash
  machine_type: n1-standard-4
- name: winagent
  image: kmo-instruqt/windows-agent
  machine_type: n1-standard-2
