version: "2"
virtualmachines:
- name: puppet
  image: kmo-instruqt/puppet
  shell: /bin/bash
  machine_type: n1-highcpu-16
- name: linux1
  image: kmo-instruqt/linux-node-no-agent
  shell: /bin/bash
  machine_type: n1-standard-8
- name: linux2
  image: kmo-instruqt/linux-node-no-agent
  shell: /bin/bash
  machine_type: n1-standard-8
