version: "2"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
  memory: 512
virtualmachines:
- name: puppet
  image: kmo-instruqt/puppet
  shell: /bin/bash
  machine_type: n1-standard-4
- name: linux1
  image: centos-7-v20201014
  shell: /bin/bash
  machine_type: n1-standard-2
- name: windows
  image: kmo-instruqt/puppet-windows
  machine_type: n1-standard-2
- name: linux2
  image: centos-8-v20210701
  shell: /bin/bash
  machine_type: n1-standard-2
