version: "2"
virtualmachines:
- name: puppet
  image: kmo-instruqt/puppet
  shell: /bin/bash
  machine_type: n1-standard-4
- name: nixagent
  image: centos-8-v20210701
  shell: /bin/bash
  machine_type: n1-standard-1
